log stdout
!
hostname rs1
!
interface lo
 ip address 100.64.10.10/32
!
router bgp 64510
 bgp router-id 100.64.10.10
 no bgp ebgp-requires-policy
 neighbor 10.0.4.3 remote-as 64511
 neighbor 10.0.4.3 local-role rs-server
 neighbor 10.0.4.4 remote-as 64512
 neighbor 10.0.4.4 local-role rs-server
 neighbor 10.0.7.3 remote-as 64703
 neighbor 10.0.7.3 local-role rs-server
 !
 address-family ipv4 unicast
  neighbor 10.0.4.3 activate
  neighbor 10.0.4.4 activate
  neighbor 10.0.7.3 activate
 exit-address-family
!
line vty
!
