log stdout
!
hostname m4
!
router bgp 64704
 bgp router-id 100.64.74.4
 no bgp ebgp-requires-policy
 neighbor 10.0.8.2 remote-as 64504
 neighbor 10.0.8.2 local-role customer
 !
 address-family ipv4 unicast
  neighbor 10.0.8.2 activate
 exit-address-family
!
line vty
!
