# config.yaml
# baseURL: http://localhost:1313/
baseURL: https://amrelhusseiny.github.io/
buildDrafts: true
theme: "m10c"
title: "Amr ElHusseiny's Blog"
languageCode: "en-us"
publishDir: "docs"


module:
  hugoVersion:
    extended: true

params:
  author: Amr ElHusseiny
  avatar: "amr_photo.png"
  description: Network engineer and Automation advocate
  menu_item_separator: "<br>"
  favicon: "favicon.ico"
  style:
    ## SideBar Color
    darkestColor: "#FFFFFF"
    ## Text Color
    darkColor: "#FFFFFF"
    ## Link Colors (Menu and Blog Header Menus)
    primaryColor: "#3e4041"
    ## Body Font Color
    lightColor: "#57595b"
    ## Headers Color
    lightestColor: "#3e4041"
  social:
    - icon: "github"
      name: "amrelhusseiny Github"
      url: "https://github.com/amrelhusseiny"
    - icon: "linkedin"
      name: "amrelhusseiny linkedin"
      url: "https://www.linkedin.com/in/amr-abd-el-halim-2a330456"

menu:
  main:
    - identifier: "Blog"
      name: "Blog"
      url: "/blog"
    - identifier: "About"
      name: "About"
      url: "/About"