# config.yaml
# baseURL: http://localhost:1313/
baseURL: https://amrelhusseiny.github.io/
buildDrafts: false
theme: "m10c"
title: "Amro Elhusseini"
languageCode: "en-us"
publishDir: "docs"


module:
  hugoVersion:
    extended: true

params:
  author: Amro Elhusseini
  avatar: "amr_photo.jpeg"
  description: Network engineer and Automation advocate
  menu_item_separator: "<br>"
  favicon: "favicon.ico"
  social:
    - icon: "github"
      name: "amrelhusseiny Github"
      url: "https://github.com/amrelhusseiny"
    - icon: "linkedin"
      name: "amrelhusseiny linkedin"
      url: "https://www.linkedin.com/in/amr-abd-el-halim-2a330456"

  style:
    darkestColor: "#ffffff"
    darkColor: "#ffffff"
    lightColor: "#353b43"
    lightestColor: "#242930"
    primaryColor: "#666666"
  relativeURLs: true

  

markup:
  goldmark:
    renderer:
      # Enabled to embed HTML Code into markdown
      unsafe: true

menu:
  main:
    - identifier: "Technical Blog"
      name: "Blog"
      url: "/blog"
    # - identifier: "Non Technical Blog"
    #   name: "non_technical"
    #   url: "/non_technical/"
    - identifier: "About"
      name: "About"
      url: "/About"
