log stdout
!
hostname rsclient2
!
interface lo
 ip address 100.64.12.12/32
!
ip route 203.0.114.0/24 Null0
!
router bgp 64512
 bgp router-id 100.64.12.12
 no bgp ebgp-requires-policy
 neighbor 10.0.4.2 remote-as 64510
 neighbor 10.0.4.2 local-role rs-client
 !
 address-family ipv4 unicast
  network 203.0.114.0/24
  neighbor 10.0.4.2 activate
 exit-address-family
!
line vty
!
