log stdout
!
hostname m5
!
router bgp 64705
 bgp router-id 100.64.75.5
 no bgp ebgp-requires-policy
 neighbor 10.0.9.2 remote-as 64503
 !
 address-family ipv4 unicast
  neighbor 10.0.9.2 activate
 exit-address-family
!
line vty
!
