!
! r2 - transit router, PRIMARY path.
!
! PRIMARY PATH : rc1 -> r1 -> r2 -> rc2
! STANDBY PATH : rc1 -> r3 -> r4 -> rc2
ip forwarding
!
interface eth0
 description uplink to r2
 ip address 10.90.0.13/24
!
interface lo
 ip address 10.90.2.2/32
!
! ---- static routes (persisted in frr.conf, not poked in at runtime) ----
ip route 10.90.1.1/32 10.90.0.11
ip route 10.90.8.1/32 10.90.0.14
!
line vty

