log stdout
!
hostname m3
!
router bgp 64703
 bgp router-id 100.64.73.3
 no bgp ebgp-requires-policy
 neighbor 10.0.7.2 remote-as 64510
 neighbor 10.0.7.2 local-role peer
 !
 address-family ipv4 unicast
  neighbor 10.0.7.2 activate
 exit-address-family
!
line vty
!
