frr version 8.1
frr defaults traditional
hostname r1
no ipv6 forwarding
!
! Path 1 only
interface eth1
 ip address 10.20.11.2/30
!
interface eth2
 ip address 10.20.12.1/30
!
interface lo
 ip address 1.1.1.11/32
!
! Toward vm1 via RC1, toward vm2 via R2
ip route 10.10.10.0/30 10.20.11.1
ip route 10.20.13.0/30 10.20.12.2
ip route 10.10.20.0/30 10.20.12.2
!
line vty
!
