log stdout
!
hostname peer1
!
interface lo
 ip address 100.64.2.2/32
!
ip route 198.51.100.0/24 Null0
!
router bgp 64502
 bgp router-id 100.64.2.2
 no bgp ebgp-requires-policy
 neighbor 10.0.1.2 remote-as 64503
 neighbor 10.0.1.2 local-role peer
 neighbor 10.0.6.3 remote-as 64702
 neighbor 10.0.6.3 local-role peer
 !
 address-family ipv4 unicast
  network 198.51.100.0/24
  neighbor 10.0.1.2 activate
  neighbor 10.0.6.3 activate
 exit-address-family
!
line vty
!
