frr version 8.4_git
frr defaults traditional
hostname customer1
domainname AUTOEVER.EUCORP.LOCAL
log stdout
no ipv6 forwarding
!
interface lo
 ip address 100.64.4.4/32
exit
!
router bgp 64504
 bgp router-id 100.64.4.4
 no bgp ebgp-requires-policy
 neighbor 10.0.2.2 remote-as 64503
 neighbor 10.0.2.2 local-role customer
 neighbor 10.0.3.3 remote-as 64505
 neighbor 10.0.3.3 local-role customer
 neighbor 10.0.8.3 remote-as 64704
 neighbor 10.0.8.3 local-role customer
exit
!
