log stdout
!
hostname m1
!
router bgp 64701
 bgp router-id 100.64.71.1
 no bgp ebgp-requires-policy
 neighbor 10.0.5.2 remote-as 64503
 neighbor 10.0.5.2 local-role peer
 !
 address-family ipv4 unicast
  neighbor 10.0.5.2 activate
 exit-address-family
!
line vty
!
