log stdout
!
hostname m2
!
router bgp 64702
 bgp router-id 100.64.72.2
 no bgp ebgp-requires-policy
 neighbor 10.0.6.2 remote-as 64502
 neighbor 10.0.6.2 local-role provider
 !
 address-family ipv4 unicast
  neighbor 10.0.6.2 activate
 exit-address-family
!
line vty
!
