log stdout
!
hostname provider2
!
interface lo
 ip address 100.64.5.5/32
!
router bgp 64505
 bgp router-id 100.64.5.5
 no bgp ebgp-requires-policy
 neighbor 10.0.3.2 remote-as 64504
 neighbor 10.0.3.2 local-role provider
 !
 address-family ipv4 unicast
  neighbor 10.0.3.2 activate
 exit-address-family
!
line vty
!
